'use client';
import './styles/globals.css'
import type { Metadata } from 'next'
import { Provider } from 'react-redux'
import { store } from '@/services/store'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <head>
          <link rel="icon" href="/night-learn-logo.png" />
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#ffffff" />
          <link rel="apple-touch-icon" href="/night-learn-logo.png" />
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />

        </head>
        <body>{children}</body>
      </html>
    </Provider>
  )
}
